title: Neeraj Goyal
email: neerajgoyal12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineering Manager with over 10 years of experience in building scalable and reliable software systems. 
  Passionate about building high performing teams and delivering high quality software products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: witty_sarcasm
github_username:  neerajgoyal12

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
